[changelog]
header = ""
body = """
{% set breaking = commits | filter(attribute="breaking", value=true) %}\
{% if breaking | length > 0 %}
### ⚠ BREAKING CHANGES
{% for commit in breaking %}
{{ self::getCommitText(commit=commit, message=commit.breaking_description) }}
{% endfor %}
{% endif %}\

{% for group, commits in commits | filter(attribute="group") | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
{{ self::getCommitText(commit=commit, message=commit.message) }}
{% endfor %}
{% endfor %}\n

{%- macro getCommitText(commit, message) -%}
  - {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})\
{%- endmacro -%}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
filter_commits = true
protect_breaking_commits = true
commit_parsers = [
  { message = "^feat",   group = "<!-- 0 -->Features" },
  { message = "^fix",    group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf",   group = "<!-- 2 -->Performance Improvements" },
  { message = "^revert", group = "<!-- 3 -->Reverts" },
  { message = ".*",      skip  = true },
]